[build]
  command = "pnpm build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["public/bps_index.json"]

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200